version: '3.8'

services:
  events_api:
    image: nestjs-docker
    container_name: events_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    env_file:
      - .env.dev
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - events_db

  events_db:
    image: postgres
    container_name: events_db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env.dev
